version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: sit-postgres
    environment:
      POSTGRES_DB: sit_db
      POSTGRES_USER: sit_user
      POSTGRES_PASSWORD: sit_pass
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: